export const mainCarouselData=[
    {
        image:"https://www.ethnicplus.in/media/mageplaza/bannerslider/banner/image/3/_/3_banarasi_saree.jpg",
        path:"/women/clothing/women_sareee"
    },
    {
        image:"https://www.ethnicplus.in/media/mageplaza/bannerslider/banner/image/2/4/24_anarkali_suits_copy_1.jpg",
        path:"/women/clothing/women_dress"
    },
    {
        image:"https://www.ethnicplus.in/media/mageplaza/bannerslider/banner/image/3/1/31_kurti_coll_copy_1.jpg",
        path:"/women/clothing/women_dress"
    },
    {
        image:"https://www.ethnicplus.in/media/mageplaza/bannerslider/banner/image/1/5/15_party_wear_lehenga.jpg",
        path:"/women/clothing/women_dress"
    },
    {
        image:"https://www.ethnicplus.in/media/mageplaza/bannerslider/banner/image/2/3/23_pant_salwar_suits_copy_2.jpg",
        path:"/women/clothing/women_dress"
    }
]